### ISSUE TITLE
Deprecation of basic authentication with password and username for Jira

### ISSUE THREAD

**Issue by Fabbby** [softvis-research/jqa-jira-plugin#11]
Currently, authentication via Rest endpoint is not possible in Jira with password and username. The future authentication should be done via API token, OAuth, or Atlassian Connect.

```xml
<jira-configuration>

    <url>http://dummy-url.com</url>
    <credentials>
        <username>login-name-for-jira</username>
       <password>jira-password</password>
    </credentials>

    <projects>
        <project>
            <key>PX</key>
        </project>        
        <project>
            <key>PY</key>
        </project>
    </projects>

</jira-configuration>
```

**Comment by b-pos465** [comment]
Thank you for your interest in the Jira plugin!

We just released a new version [v0.0.3](https://github.com/softvis-research/jqa-jira-plugin/releases/tag/v0.0.3) which allows using **API token authentication**. Please read the [README](https://github.com/softvis-research/jqa-jira-plugin) for a valid XML configuration. There you can also find the information on how to get an API key for **Atlassian**.

Version _v0.0.3_ was tested with the [jQAssistant 1.8.0 command line distribution](https://jqassistant.org/wp-content/uploads/2020/01/jqassistant-commandline-neo4jv3-1.8.0-distribution.zip) against an official Jira DEV cloud test environment: https://jqa-jira-plugin.atlassian.net/.
